### ISSUE TITLE
Missing decimal mode

### ISSUE THREAD

**Issue by boomlinde** [ITotalJustice/6502#2]
I realize that this is primarily intended for NES where decimal mode has been omitted, but as a 6502 emulator I think it should at least optionally support it. This will only affect the adc/sbc implementations. I am willing to contribute these changes under the unlicense if you will accept pull requests, or preferably as just a patch file!

**Comment by ITotalJustice** [comment]
I was meaning the add decimal mode at some point, sadly i never got around to it. If you'd be willing to send a patch that would be great! Either as a PR or a patch file will be fine. If sent as a patch file, i'll apply the patch my end then commit the changes. Though a PR would be easier if you are able to 😃

**Comment by boomlinde** [comment]
Cool, a PR it is!

I've begun work on this now. It's quite a head scratcher but I've built a test suite that covers all combinations of possible operands and carry/decimal flags with a truth table generated by a verified emulator, so I feel more confident now.

**Comment by ITotalJustice** [comment]
closed thanks to #3
